### ISSUE TITLE
Load the pipeline once and for all

### ISSUE THREAD

**Issue by sadaqabdo** [amine759/QA-Web-App#1]
This line of instantiating the qa pipeline will execute on every run of predict function: 

https://github.com/amine759/QA-Web-App/blob/9573102dda0fbca460cbcb8923c69836148654a0/app.py#L31

this might not be efficient, try to run it on the app startup instead. 🤗

**Comment by amine759** [comment]
@sadaqabdo **once and for all** you're goddamn right, I will edit it, thanks for mentioning.  :open_hands:
